### PR TITLE
ported to 3.3, usual way

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
ping :)

**Comment by ThomasWaldmann** [comment]
hmm, what's the current state of this?

**Comment by mitsuhiko** [comment]
I will have a look at that.

**Comment by amitu** [comment]
Hey, I am planning to use this library for another library, importd, and python 3.3. support is required. Can you please speed this up?

**Comment by ThomasWaldmann** [comment]
ping

**Comment by ThomasWaldmann** [comment]
I'm killing all my github repos that I don't actively use.
So, if you'ld like to pull this, do it asap or reject it if not.

**Comment by homeworkprod** [comment]
BTW, does this mean that 'speaklater', in it's release form, is not compatible with Python 3(.3)?

**Comment by ThomasWaldmann** [comment]
Closing, sick of waiting.

**Pull request closed without merging**
